from __future__ import annotations

import importlib.util
import math
from datetime import date, timedelta
from pathlib import Path

import numpy as np
import polars as pl

from congressional_sales import storage

REPO_ROOT = Path(__file__).resolve().parents[1]

CONGRESS_TRADES_SCHEMA = {
    "ticker": pl.Utf8, "politician": pl.Utf8, "bioguide_id": pl.Utf8, "chamber": pl.Utf8,
    "party": pl.Utf8, "transaction": pl.Utf8, "transaction_date": pl.Date, "report_date": pl.Date,
    "amount_low": pl.Float64, "amount_range": pl.Utf8, "ticker_type": pl.Utf8, "description": pl.Utf8,
    "excess_return": pl.Float64, "price_change": pl.Float64, "spy_change": pl.Float64,
}
PRICE_SCHEMA = {
    "ticker": pl.Utf8, "date": pl.Date, "open": pl.Float64, "high": pl.Float64,
    "low": pl.Float64, "close": pl.Float64, "volume": pl.Float64, "close_adj": pl.Float64,
}
FACTOR_SCHEMA = {"date": pl.Date, "mkt_rf": pl.Float64, "smb": pl.Float64, "hml": pl.Float64, "mom": pl.Float64, "rf": pl.Float64}
TERMS_SCHEMA = {
    "bioguide_id": pl.Utf8, "full_name": pl.Utf8, "chamber": pl.Utf8,
    "term_start": pl.Date, "term_end": pl.Date, "state": pl.Utf8, "party": pl.Utf8,
}
SIC_SCHEMA = {"ticker": pl.Utf8, "cik": pl.Int64, "sic_code": pl.Utf8, "sic_description": pl.Utf8}
ASSIGNMENTS_SCHEMA = {"bioguide_id": pl.Utf8, "committee_code": pl.Utf8, "committee_name": pl.Utf8, "chamber": pl.Utf8}
HISTORICAL_ASSIGNMENTS_SCHEMA = {
    "bioguide_id": pl.Utf8, "committee_name": pl.Utf8, "chamber": pl.Utf8,
    "assignment_start": pl.Date, "assignment_end": pl.Date,
}

# Business Equipment (AAA1, AAA2), Energy (ENR1, ENR2) -- two sectors, so
# Model 2's IndustryFE has real (>1-level) variation, and same-sector
# size/industry-matched CAR has a real peer to compute against. This is
# exactly the bug class this project's own live sanity check found
# (AAPL/MSFT/NVDA were all one sector, degenerating IndustryFE).
TICKERS_BY_SECTOR = {"7372": ["AAA1", "AAA2"], "2911": ["ENR1", "ENR2"]}
ALL_TICKERS = [t for tickers in TICKERS_BY_SECTOR.values() for t in tickers]
SECTOR_OF = {t: sic for sic, tickers in TICKERS_BY_SECTOR.items() for t in tickers}
BUSINESS_EQUIPMENT_COMMITTEE = "House Committee on Science, Space, and Technology"
ENERGY_COMMITTEE = "Senate Committee on Energy and Natural Resources"

N_MEMBERS = 40
MEMBERS = [f"M{i}" for i in range(1, N_MEMBERS + 1)]
CONTINUOUS_YEARS = list(range(2014, 2025))  # 2014-2024, inside the funnel's own sample period
YEARS_POOL = [2016, 2017, 2018, 2019, 2020, 2021, 2022]  # candidate years for sparse traders
HOLDOUT_YEAR = 2025  # inside both scripts' hardcoded 2024-07-01..2025-12-31 holdout window

BANDS = ["$1,001 - $15,000", "$15,001 - $50,000", "$50,001 - $100,000"]


def _build_member_profiles() -> dict[str, dict]:
    """One profile per member, generated by a SEEDED random draw rather
    than a hand-picked pattern.

    This fixture went through several hand-crafted designs before landing
    here, each of which produced an EXACT linear dependency somewhere in
    Model 2's design matrix once fixed effects were absorbed -- industry
    exactly reducible to a member-dummy subset, committee_match or
    opportunistic constant per member (and therefore exactly reducible to
    the same thing), sale_x_opportunistic exactly equal to sale across the
    whole panel. Every fix required is documented in this project's git
    history for this file. A deterministic pattern applied uniformly
    across many members reliably reproduces the SAME identity on every
    member it touches; independent random draws per member essentially
    never do, which is why tests/test_robustness.py's and
    tests/models/test_multiple_comparisons.py's own Model 2 fixtures use
    exactly this approach rather than a hand-built panel. `type` controls
    which calendar months (if any) are traded continuously every year
    (giving real, month-specific is_routine variation); `cross_sector`
    controls whether the June leg trades a different-sector ticker than
    the February leg (giving real within-member industry variation, the
    same mechanism that also gives committee_match real within-member
    variation when paired with a committee matching only one sector).
    """
    rng = np.random.default_rng(20260812)
    profiles = {}
    for m in MEMBERS:
        feb_ticker = rng.choice(ALL_TICKERS)
        cross_sector = rng.random() < 0.30
        if cross_sector:
            other_sector_tickers = [t for t in ALL_TICKERS if SECTOR_OF[t] != SECTOR_OF[feb_ticker]]
            jun_ticker = rng.choice(other_sector_tickers)
        else:
            jun_ticker = feb_ticker
        member_type = rng.choice(["continuous_both", "continuous_feb", "continuous_jun", "sparse"])
        committee_choice = rng.choice(["none", "match_feb_sector", "match_other_sector"], p=[0.4, 0.3, 0.3])
        if committee_choice == "none":
            committee = None
        elif committee_choice == "match_feb_sector":
            committee = BUSINESS_EQUIPMENT_COMMITTEE if SECTOR_OF[feb_ticker] == "7372" else ENERGY_COMMITTEE
        else:
            committee = ENERGY_COMMITTEE if SECTOR_OF[feb_ticker] == "7372" else BUSINESS_EQUIPMENT_COMMITTEE
        sparse_years = sorted(int(y) for y in rng.choice(YEARS_POOL, size=4, replace=False))
        profiles[m] = {
            "feb_ticker": feb_ticker, "jun_ticker": jun_ticker, "type": member_type,
            "committee": committee, "sparse_years": sparse_years,
        }
    return profiles


MEMBER_PROFILES = _build_member_profiles()


def _load_script(name: str):
    spec = importlib.util.spec_from_file_location(name, REPO_ROOT / "scripts" / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _weekdays(start: date, end: date) -> list[date]:
    days = []
    d = start
    while d <= end:
        if d.weekday() < 5:
            days.append(d)
        d += timedelta(days=1)
    return days


def _band(member: str, d: date) -> str:
    # Independent of transaction type -- both purchases and sales draw from
    # all three bands. If amount_range instead deterministically tracked
    # purchase-vs-sale, size_band's dummy would be perfectly collinear with
    # `sale` itself (confirmed empirically during this fixture's development).
    return BANDS[hash((member, d)) % len(BANDS)]


def _seed_warehouse() -> None:
    calendar_start, calendar_end = date(2013, 1, 1), date(2026, 9, 30)
    sessions = _weekdays(calendar_start, calendar_end)

    # --- Prices: SPY (market anchor) + 4 tickers (independent positive
    # geometric random walks -- exp() keeps every price strictly positive
    # regardless of drawdown, no clamping needed).
    rng = np.random.default_rng(2026)
    price_rows = []
    for i, d in enumerate(sessions):
        price_rows.append(
            {"ticker": "SPY", "date": d, "open": 1.0, "high": 1.0, "low": 1.0,
             "close": 300.0, "volume": 1_000_000.0, "close_adj": 300.0 * math.exp(0.0001 * i)}
        )
    for ticker in ALL_TICKERS:
        price = 100.0
        for d in sessions:
            price *= math.exp(float(rng.normal(0, 0.012)))
            price_rows.append(
                {"ticker": ticker, "date": d, "open": price, "high": price, "low": price,
                 "close": price, "volume": 500_000.0, "close_adj": price}
            )
    storage.write("equity_eod", pl.DataFrame(price_rows, schema=PRICE_SCHEMA), key_cols=["ticker", "date"])

    # --- Fama-French factors, every session in the calendar.
    factor_rows = [
        {
            "date": d, "mkt_rf": float(rng.normal(0, 0.005)), "smb": float(rng.normal(0, 0.003)),
            "hml": float(rng.normal(0, 0.003)), "mom": float(rng.normal(0, 0.003)), "rf": 0.00005,
        }
        for d in sessions
    ]
    storage.write("ff_factors", pl.DataFrame(factor_rows, schema=FACTOR_SCHEMA), key_cols=["date"])

    # --- SIC codes.
    sic_rows = [
        {"ticker": t, "cik": 1000 + i, "sic_code": sic, "sic_description": "x"}
        for sic, tickers in TICKERS_BY_SECTOR.items()
        for i, t in enumerate(tickers)
    ]
    storage.write("sic_codes", pl.DataFrame(sic_rows, schema=SIC_SCHEMA), key_cols=["ticker"])

    # --- Legislator terms: three staggered terms per member (a distinct
    # offset per member), the LAST of which ends far in the future so
    # Screen 3's retirement-window sub-condition never fires.
    # build_model2_frame's seniority_terms = count of terms with
    # term_start < report_date.
    #
    # Two collinearities this fixture hit here, in order. (1) A SHARED
    # schedule across every member makes seniority_terms constant within
    # any single calendar year (every member has accumulated the same
    # count on the same calendar) -- exactly as collinear with a per-year
    # fit's MemberFE as a never-changing value would be; distinct
    # per-member offsets fixed this ACROSS years. (2) Even with distinct
    # offsets, term_start on January 3rd means seniority_terms is constant
    # for a given member's OWN two rows within any single year (its Feb
    # purchase and June sale both fall after the same January term-start
    # date, so neither ever sees a different count than the other) --
    # per-member-constant-within-a-year is exactly as collinear with that
    # year's MemberFE as a global constant, the same structural problem
    # industry (fixed via M-crosser tickers) and committee_match (fixed
    # via a committee matching only one sector) already hit -- confirmed
    # via AbsorbingLS's own drop_absorbed=True diagnostic, which named
    # seniority_terms as the sole absorbed variable once every other
    # collinearity in this fixture was already fixed. Moving term_start to
    # April 1st -- between each year's own February purchase and June sale
    # -- means any member whose term boundary falls in year Y has
    # DIFFERENT seniority_terms on their two Y-dated rows, not just
    # different values across years.
    terms_rows = []
    for offset, m in enumerate(MEMBERS):
        for term_start, term_end in (
            (date(2005 + offset % 15, 4, 1), date(2015 + offset % 15, 4, 1)),
            (date(2015 + offset % 15, 4, 1), date(2021 + offset % 15, 4, 1)),
            (date(2021 + offset % 15, 4, 1), date(2040, 1, 3)),
        ):
            terms_rows.append(
                {"bioguide_id": m, "full_name": m, "chamber": "rep", "term_start": term_start, "term_end": term_end, "state": "XX", "party": "R"}
            )
    storage.write("legislator_terms", pl.DataFrame(terms_rows, schema=TERMS_SCHEMA), key_cols=["bioguide_id", "chamber", "term_start"])

    # --- Committee assignments (current-only snapshot): per MEMBER_PROFILES.
    committee_rows = [
        {"bioguide_id": m, "committee_code": f"C{i:03d}", "committee_name": profile["committee"], "chamber": "house"}
        for i, (m, profile) in enumerate(MEMBER_PROFILES.items())
        if profile["committee"] is not None
    ]
    storage.write("committee_assignments", pl.DataFrame(committee_rows, schema=ASSIGNMENTS_SCHEMA), key_cols=["bioguide_id", "committee_code"])

    # --- Historical committee assignments: light integration coverage for
    # the feature this session added (sample.classify.committee_match's
    # historical_assignments path) -- M1 held a non-matching committee
    # before 2016-04-01 and its real (matching-if-any) committee after.
    # Not load-bearing for this fixture's degrees-of-freedom problem (the
    # random member pool above solves that on its own); this exists so the
    # end-to-end test actually exercises the historical lookup at all, not
    # just its own unit tests.
    m1_committee = MEMBER_PROFILES["M1"]["committee"] or BUSINESS_EQUIPMENT_COMMITTEE
    storage.write(
        "committee_assignments_historical",
        pl.DataFrame(
            [
                {"bioguide_id": "M1", "committee_name": "House Committee on Agriculture", "chamber": "house", "assignment_start": date(2005, 1, 3), "assignment_end": date(2016, 3, 31)},
                {"bioguide_id": "M1", "committee_name": m1_committee, "chamber": "house", "assignment_start": date(2016, 4, 1), "assignment_end": None},
            ],
            schema=HISTORICAL_ASSIGNMENTS_SCHEMA,
        ),
        key_cols=["bioguide_id", "committee_name", "assignment_start"],
    )

    # --- Congressional trades, from MEMBER_PROFILES.
    #
    # Every member buys in February (large amount, building cumulative
    # exposure) and sells in June (small amount, well under 60% of that
    # exposure, so Screen 3(a) never fires) of every year they trade.
    # Feb->June is ~120 days, safely outside Screen 1's 90-day rebalancing
    # window; nothing trades in Nov/Dec, so Screen 2 never fires either.
    # "continuous_*" members trade the named month(s) every year
    # 2014-2024; everyone trades their own 4 randomly chosen YEARS_POOL
    # years regardless of type, plus once more in the holdout year.
    trade_rows = []

    def _purchase(member: str, ticker: str, d: date) -> None:
        trade_rows.append(
            {
                "ticker": ticker, "politician": member, "bioguide_id": member, "chamber": "Representatives",
                "party": "R", "transaction": "Purchase", "transaction_date": d, "report_date": d,
                "amount_low": 50_000.0, "amount_range": _band(member, d), "ticker_type": "ST", "description": None,
                "excess_return": None, "price_change": None, "spy_change": None,
            }
        )

    def _sale(member: str, ticker: str, d: date) -> None:
        trade_rows.append(
            {
                "ticker": ticker, "politician": member, "bioguide_id": member, "chamber": "Representatives",
                "party": "R", "transaction": "Sale", "transaction_date": d, "report_date": d,
                "amount_low": 5_000.0, "amount_range": _band(member, d), "ticker_type": "ST", "description": None,
                "excess_return": None, "price_change": None, "spy_change": None,
            }
        )

    for m, profile in MEMBER_PROFILES.items():
        feb_years = set(profile["sparse_years"]) | {HOLDOUT_YEAR}
        jun_years = set(profile["sparse_years"]) | {HOLDOUT_YEAR}
        if profile["type"] in ("continuous_both", "continuous_feb"):
            feb_years |= set(CONTINUOUS_YEARS)
        if profile["type"] in ("continuous_both", "continuous_jun"):
            jun_years |= set(CONTINUOUS_YEARS)
        for year in sorted(feb_years):
            _purchase(m, profile["feb_ticker"], date(year, 2, 1))
        for year in sorted(jun_years):
            _sale(m, profile["jun_ticker"], date(year, 6, 1))

    storage.write(
        "congress_trades", pl.DataFrame(trade_rows, schema=CONGRESS_TRADES_SCHEMA),
        key_cols=["ticker", "bioguide_id", "transaction_date", "transaction", "amount_range"],
    )


def test_full_pipeline_and_holdout_produce_a_bh_pvalue_a_t8_and_an_f7(tmp_path, monkeypatch):
    """Runs the real run_full_pipeline.py and run_holdout.py entry points
    (via importlib, not subprocess -- same in-process pattern every other
    test in this suite uses, imported by file path since scripts/ is not a
    package) against a fully synthetic warehouse, and checks the three
    concrete artifacts this project's own walkthrough flagged as
    previously unverified by any automated test:

      1. A real, computed Benjamini-Hochberg p-value in
         bh_correction_grid.csv (not just a "not yet computed" placeholder).
      2. A non-empty T8 (outputs/t8_holdout.csv), written by run_holdout.py.
      3. F7 (outputs/f7_year_by_year_effect.png) actually generated.

    This is the one end-to-end test closing the gap the walkthrough's Test
    Coverage Gaps section named explicitly: "No test exercises
    run_full_pipeline.py or run_holdout.py themselves."
    """
    monkeypatch.setenv("CONGRESS_SALES_HOME", str(tmp_path / "wh"))
    storage.paths().ensure()
    _seed_warehouse()

    run_full_pipeline = _load_script("run_full_pipeline")
    run_full_pipeline.main()

    outputs = storage.paths().outputs
    assert (outputs / "paper.md").exists()
    assert (outputs / "f7_year_by_year_effect.png").exists(), "F7 was not generated"

    bh_grid = pl.read_csv(outputs / "bh_correction_grid.csv")
    assert bh_grid.height == 18
    non_null_p = bh_grid.filter(pl.col("p_value").is_not_null())
    assert non_null_p.height > 0, "no cell in the 18-variant grid produced a usable p-value"
    for p in non_null_p["p_value"].to_list():
        assert 0.0 <= p <= 1.0

    paper_md = (outputs / "paper.md").read_text()
    assert "not yet computed" not in paper_md.lower()

    run_holdout = _load_script("run_holdout")
    run_holdout.main()

    t8 = pl.read_csv(outputs / "t8_holdout.csv")
    assert t8.height > 0
    assert "sale" in t8["param"].to_list()

    paper_md_after_holdout = (outputs / "paper.md").read_text()
    assert "## Table T8" in paper_md_after_holdout
